import webbrowser
edge_path = "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
webbrowser.register('windows-default', None, webbrowser.BackgroundBrowser(edge_path))
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=oui&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=non&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=caca&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=pipi&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=ezrazr&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=fqf&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=fdbdfdf&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=jgfdkjjgdsf&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=jkfdsjgfds&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=dfsgdff&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=fddsdfgg&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=nontz&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=nons&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=nezraon&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=norgfdn&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=nouyyjn&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=norterzn&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=noazdqsn&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=ezfsd&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=zaerfnon&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=ouyuj&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=fdggdpglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=fdgdfsg&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=ngdsfgdg&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=nqdsqss&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=opuiytr&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=nazazrzaron&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=ndsfgdgson&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=fdsgg&pglt=931&FORM=ANNTA1')
webbrowser.get('windows-default').open('https://www.bing.com/search?PC=U523&q=fdsssdg&pglt=931&FORM=ANNTA1')